export const guestCopy = {
  title: "小柜大爱",
  subtitle: "先了解服务、查看柜机物资，领取时再登录核验资格。",
  nearbyTitle: "查找柜机",
  nearbySubtitle: "查看柜机位置、物资和库存，选择方便到达的柜机。",
  detailSubtitle: "库存随实际领取更新；个人领取权益在登录后显示。",
  serviceTitle: "社区公益物资服务",
  serviceBody: "小柜大爱为有需要的居民提供公益物资。您可以先查看柜机位置和现有物资；实际领取需要核验服务资格与当天权益。",
  steps: ["查看柜机与物资", "需要领取时登录核验资格", "到柜机现场扫码，关门后按实际领取记录权益"],
  browse: "查看柜机和物资",
  continueBrowse: "暂不登录，继续浏览",
  login: "登录 / 注册",
  loginPurpose: "手机号用于确认领取身份、查询本人权益和领取记录。浏览柜机及物资无需登录。",
  pickupLogin: "登录查看领取权益",
  help: "领取帮助",
  devices: "柜机列表",
  detail: "查看物资与库存",
  refresh: "刷新库存",
  loading: "正在读取柜机库存…",
  failed: "暂时无法读取库存，请稍后重试。",
  emptyDevices: "当前暂无已配置的柜机。",
  emptyGoods: "此柜机暂未配置物资，请查看其他柜机。",
  stock: (quantity: number) => `当前可用库存 ${quantity} 件`,
  emptyStock: "暂时无货",
  inactive: "暂停领取",
  status: { online: "在线", offline: "离线", maintenance: "维护中" },
  recordsTitle: "我的领取记录",
  recordsBody: "登录后可查看本人的领取记录。您也可以继续浏览柜机和物资。",
  accountTitle: "我的账户",
  accountBody: "需要查看个人权益、提交领取资格资料时，可自行选择登录。",
  imageFallback: "公益物资"
} as const;
