export const guestCopy = {
  title: "商品列表",
  subtitle: "按需领取，取物后请关好柜门。",
  browse: "浏览商品",
  continueBrowse: "暂不登录，继续浏览",
  login: "登录 / 注册",
  loginPurpose: "手机号用于核验领取身份，查询本人权益和领取记录。",
  scan: "扫码开柜",
  scanning: "正在扫码…",
  scanFailed: "未能完成扫码，请重试。",
  help: "领取帮助",
  refresh: "重新加载",
  loading: "正在加载商品…",
  failed: "商品暂未加载，请重试。",
  emptyProducts: "暂无商品",
  recordsTitle: "我的领取记录",
  recordsBody: "登录后查看本人的领取记录。",
  accountTitle: "我的账户",
  accountBody: "登录后查看权益或提交领取资格资料。",
  imageFallback: "商品"
} as const;
