export const guestCopy = {
  title: "小柜大爱",
  subtitle: "查看附近柜机和公益物资。",
  nearbyTitle: "查找柜机",
  nearbySubtitle: "查看柜机位置和物资库存。",
  detailSubtitle: "到柜机前扫码，按本人权益领取。",
  serviceTitle: "领取指引",
  serviceBody: "按需领取公益物资，取物后请关好柜门。",
  steps: ["查看柜机与库存", "登录查看领取权益", "到柜机扫码开门，取物后关门"],
  browse: "查看柜机和物资",
  continueBrowse: "暂不登录，继续浏览",
  login: "登录 / 注册",
  loginPurpose: "手机号用于核验领取身份，查询本人权益和领取记录。",
  pickupLogin: "登录查看领取权益",
  help: "领取帮助",
  devices: "柜机列表",
  detail: "查看物资与库存",
  refresh: "刷新库存",
  loading: "正在读取柜机库存…",
  failed: "暂时无法读取库存，请稍后重试。",
  emptyDevices: "当前暂无可用柜机。",
  emptyGoods: "此柜机暂无物资，请查看其他柜机。",
  stock: (quantity: number) => `库存 ${quantity} 件`,
  emptyStock: "暂时无货",
  inactive: "暂停领取",
  status: { online: "在线", offline: "离线", maintenance: "维护中" },
  recordsTitle: "我的领取记录",
  recordsBody: "登录后查看本人的领取记录。",
  accountTitle: "我的账户",
  accountBody: "登录后查看权益或提交领取资格资料。",
  imageFallback: "公益物资"
} as const;
